ci: enables husky

diff --git a/functions/.husky/pre-commit b/functions/.husky/pre-commit
--- a/functions/.husky/pre-commit
+++ b/functions/.husky/pre-commit
@@ -1,2 +1,9 @@
 echo "running pre-commit checks..."
+# Do not commit to main branch
+if [ "$(git symbolic-ref --short HEAD)" = "main" ]; then
+  echo "Cannot commit to main branch"
+  exit 1
+fi
+# Run lint check
+cd functions
 lint-staged
